#!/usr/bin/env node
/**
 * `create-settle-merchant` — public npx entry point.
 *
 * Usage:
 *   npx create-settle-merchant <name>
 *
 * Generates everything a new merchant needs to start accepting Settle:
 *   - merchant keypair (64-byte secret + base58 pubkey)
 *   - HMAC webhook signing secret
 *   - one starter capability hash for an example tool
 *   - .env.template with the right variable names
 *   - merchant.md README
 *   - .gitignore
 *
 * All output lands in `./<name>/`. Re-running with the same name fails fast
 * so the keypair is never silently overwritten.
 *
 * D1 / Wave 2 — published as a standalone npm package, no monorepo deps.
 * The capability-hash derivation is inlined (mirrors @settle/sdk
 * `computeCapabilityHashHex`) so the package has no workspace coupling.
 */
import { Keypair } from "@solana/web3.js";
import bs58 from "bs58";
import { blake3 } from "@noble/hashes/blake3";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { randomBytes } from "node:crypto";

const KEYPAIR_PERMS = 0o600;

function nameFromArgv(): string {
  const arg = process.argv[2]?.trim();
  if (!arg || arg === "--help" || arg === "-h") {
    printUsage();
    process.exit(arg ? 0 : 1);
  }
  if (!/^[a-z0-9-]{2,64}$/.test(arg)) {
    console.error(
      "Merchant name must be 2-64 chars of lowercase letters, numbers, dashes.",
    );
    process.exit(1);
  }
  return arg;
}

function printUsage(): void {
  console.log("create-settle-merchant — scaffold a Settle merchant workspace");
  console.log("");
  console.log("Usage:");
  console.log("  npx create-settle-merchant <name>");
  console.log("");
  console.log("Generates ./<name>/ with:");
  console.log("  merchant.keypair.json   Solana keypair (64-byte secret)");
  console.log("  .env.template            env vars: pubkey, webhook secret, capability hash");
  console.log("  merchant.md              README explaining how to wire it into MCP/HTTP");
  console.log("  .gitignore               protects the keypair from accidental commit");
  console.log("");
  console.log("After scaffolding:");
  console.log("  cd <name>");
  console.log("  cp .env.template .env");
  console.log("  # set MERCHANT_WEBHOOK_URL, then install @settle/mcp-middleware");
}

interface CapabilitySpec {
  domain: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  amount_lamports: string;
  version: number;
}

function canonicalJsonStringify(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return `[${value.map(canonicalJsonStringify).join(",")}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([k, v]) => `${JSON.stringify(k)}:${canonicalJsonStringify(v)}`);
  return `{${entries.join(",")}}`;
}

function computeCapabilityHashHex(spec: CapabilitySpec): string {
  if (!/^\d+$/.test(spec.amount_lamports)) {
    throw new Error("amount_lamports must be a non-negative decimal string");
  }
  if (!Number.isInteger(spec.version) || spec.version < 1) {
    throw new Error("version must be a positive integer");
  }
  const normalized: CapabilitySpec = {
    domain: spec.domain.normalize("NFC"),
    method: spec.method,
    path: spec.path,
    amount_lamports: spec.amount_lamports,
    version: spec.version,
  };
  const json = canonicalJsonStringify(normalized);
  const bytes = new TextEncoder().encode(json);
  const hash = blake3(bytes);
  return Array.from(hash, (b) => b.toString(16).padStart(2, "0")).join("");
}

function main(): void {
  const name = nameFromArgv();
  const dir = resolve(process.cwd(), name);
  if (existsSync(dir)) {
    console.error(`Directory ${dir} already exists. Pick another name or remove it.`);
    process.exit(1);
  }
  mkdirSync(dir, { recursive: true });

  const merchant = Keypair.generate();
  const merchantSecret = bs58.encode(merchant.secretKey);
  const keypairPath = join(dir, "merchant.keypair.json");
  writeFileSync(keypairPath, JSON.stringify(Array.from(merchant.secretKey)));
  try {
    chmodSync(keypairPath, KEYPAIR_PERMS);
  } catch {
    // Windows / unsupported — file ACLs are documented in README.
  }

  const webhookSecret = randomBytes(32).toString("base64");

  const sampleCapability = computeCapabilityHashHex({
    domain: `${name}.example`,
    method: "POST",
    path: "/v1/example",
    amount_lamports: "10000",
    version: 1,
  });

  const envTemplate = [
    `# Generated by create-settle-merchant for "${name}"`,
    `# Keep .env out of git. Reference these from your server runtime.`,
    "",
    `MERCHANT_NAME=${name}`,
    `MERCHANT_PUBKEY=${merchant.publicKey.toBase58()}`,
    `MERCHANT_PRIVKEY_B58=${merchantSecret}`,
    `# (or load from merchant.keypair.json — same key, two formats)`,
    "",
    `# Webhook delivery: Settle signs every webhook with HMAC-SHA256(this).`,
    `SETTLE_WEBHOOK_SIGNING_SECRET=${webhookSecret}`,
    "",
    `# Optional: where Settle should POST your webhooks. If unset, no webhooks fire.`,
    `MERCHANT_WEBHOOK_URL=`,
    "",
    `# Pricing for your tools — capability_hash + amount_lamports per tool name.`,
    `SETTLE_DEMO_CAPABILITY_HASH=${sampleCapability}`,
    `SETTLE_DEMO_AMOUNT_LAMPORTS=10000`,
    "",
    `# Settle facilitator endpoint. Devnet: https://settle.so (or self-host).`,
    `SETTLE_ENDPOINT=https://settle.so`,
    "",
  ].join("\n");
  writeFileSync(join(dir, ".env.template"), envTemplate);

  const readme = [
    `# Settle merchant: ${name}`,
    "",
    `Generated by \`create-settle-merchant\`.`,
    "",
    `## Files`,
    "",
    `- \`merchant.keypair.json\` — 64-byte secret key as a JSON array.`,
    `  \`solana program deploy --keypair merchant.keypair.json\` and \`anchor\` both consume this format.`,
    `  Matching pubkey: \`${merchant.publicKey.toBase58()}\`.`,
    `- \`.env.template\` — copy to \`.env\` and source it in your server runtime.`,
    `- \`merchant.keypair.json\` is mode 600 on Linux/macOS. On Windows, set ACLs manually.`,
    "",
    `## MCP integration`,
    "",
    "```ts",
    `import { wrapWithSettle } from "@settle/mcp-middleware";`,
    "",
    "server.setRequestHandler(CallToolRequestSchema, wrapWithSettle({",
    "  handler: yourExistingHandler,",
    "  pricing: {",
    "    example: {",
    `      capability_hash: "${sampleCapability}",`,
    `      amount_lamports: "10000",`,
    "    },",
    "  },",
    `  settleEndpoint: process.env.SETTLE_ENDPOINT!,`,
    `  merchantPubkey: process.env.MERCHANT_PUBKEY!,`,
    "}));",
    "```",
    "",
    `## Plain HTTP`,
    "",
    "```ts",
    `import { requireSettleCredential } from "@settle/mcp-middleware";`,
    "",
    "const checkPayment = requireSettleCredential({",
    "  pricing: {",
    `    capability_hash: "${sampleCapability}",`,
    `    amount_lamports: "10000",`,
    "  },",
    `  settleEndpoint: process.env.SETTLE_ENDPOINT!,`,
    `  merchantPubkey: process.env.MERCHANT_PUBKEY!,`,
    "});",
    "",
    "const result = await checkPayment(req.headers);",
    `if (!result.allowed) return new Response("payment required", { status: 402 });`,
    "```",
    "",
    `## Embed pay button`,
    "",
    "```html",
    `<script src="https://settle.so/pay.js"></script>`,
    `<settle-pay merchant="${merchant.publicKey.toBase58()}" amount="0.50" note="Order"></settle-pay>`,
    "```",
    "",
    `## Register your alias`,
    "",
    `Submit your capability_hash to /capabilities so users see "Translate EN→FR"`,
    `instead of \`${sampleCapability.slice(0, 16)}…\`.`,
    "",
  ].join("\n");
  writeFileSync(join(dir, "merchant.md"), readme);

  writeFileSync(
    join(dir, ".gitignore"),
    [
      "merchant.keypair.json",
      ".env",
      ".env.local",
      "",
    ].join("\n"),
  );

  console.log(`✓ Generated ./${name}/`);
  console.log(`  pubkey:           ${merchant.publicKey.toBase58()}`);
  console.log(`  capability_hash:  ${sampleCapability.slice(0, 16)}…`);
  console.log(`  webhook secret:   (32 bytes, in .env.template)`);
  console.log("");
  console.log("Next:");
  console.log(`  1. cd ${name}`);
  console.log(`  2. cp .env.template .env`);
  console.log(`  3. npm install @settle/mcp-middleware`);
  console.log(`  4. Register your alias at https://settle.so/capabilities`);
}

main();
