#!/usr/bin/env tsx
/**
 * F4.1 — Merchant onboarding CLI.
 *
 * Run:
 *   pnpm exec tsx scripts/create-settle-merchant.ts <merchant-name>
 *
 * Generates everything a new merchant needs to start accepting Settle:
 *   - merchant keypair (64-byte secret + base58 pubkey)
 *   - HMAC webhook signing secret
 *   - one starter capability hash for an example tool
 *   - .env.template with the right variable names
 *   - merchant.md README explaining each file
 *
 * All output lands in `./<merchant-name>/` so a fresh run never clobbers
 * an existing config. The keypair file is written with restrictive perms
 * where the OS supports it (no-op on Windows; documented in the README).
 */
import { Keypair } from "@solana/web3.js";
import { computeCapabilityHashHex } from "@settle/sdk";
import bs58 from "bs58";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { randomBytes } from "node:crypto";

const KEYPAIR_PERMS = 0o600;

function nameFromArgv(): string {
  const arg = process.argv[2]?.trim();
  if (!arg) {
    console.error(
      "Usage: pnpm exec tsx scripts/create-settle-merchant.ts <merchant-name>",
    );
    console.error("       e.g. translate-demo");
    process.exit(1);
  }
  if (!/^[a-z0-9-]{2,64}$/.test(arg)) {
    console.error(
      "Merchant name must be 2-64 chars of lowercase letters, numbers, dashes.",
    );
    process.exit(1);
  }
  return arg;
}

function main() {
  const name = nameFromArgv();
  const dir = resolve(process.cwd(), name);
  if (existsSync(dir)) {
    console.error(`Directory ${dir} already exists. Pick another name or remove it.`);
    process.exit(1);
  }
  mkdirSync(dir, { recursive: true });

  // 1. Merchant keypair.
  const merchant = Keypair.generate();
  const merchantSecret = bs58.encode(merchant.secretKey);
  const keypairPath = join(dir, "merchant.keypair.json");
  // Anchor / Solana CLI compatible: array of 64 bytes.
  writeFileSync(keypairPath, JSON.stringify(Array.from(merchant.secretKey)));
  try {
    chmodSync(keypairPath, KEYPAIR_PERMS);
  } catch {
    // Windows / unsupported platforms — ignore.
  }

  // 2. Webhook signing secret (32 random bytes, base64).
  const webhookSecret = randomBytes(32).toString("base64");

  // 3. Starter capability hash for a sample tool.
  const sampleCapability = computeCapabilityHashHex({
    domain: `${name}.example`,
    method: "POST",
    path: "/v1/example",
    amount_lamports: "10000",
    version: 1,
  });

  // 4. .env.template with the right variable names.
  const envTemplate = [
    `# F4.1 — generated by create-settle-merchant for "${name}"`,
    `# Keep .env out of git. Reference these from your server runtime.`,
    "",
    `MERCHANT_NAME=${name}`,
    `MERCHANT_PUBKEY=${merchant.publicKey.toBase58()}`,
    `MERCHANT_PRIVKEY_B58=${merchantSecret}`,
    `# (or load from merchant.keypair.json — same key, two formats)`,
    "",
    `# Webhook delivery: Settle signs every webhook with HMAC-SHA256(this).`,
    `SETTLE_WEBHOOK_SIGNING_SECRET=${webhookSecret}`,
    "",
    `# Optional: where Settle should POST your webhooks. If unset, no webhooks fire.`,
    `MERCHANT_WEBHOOK_URL=`,
    "",
    `# Pricing for your tools — capability_hash + amount_lamports per tool name.`,
    `# Add aliases via /capabilities so users see human names.`,
    `SETTLE_DEMO_CAPABILITY_HASH=${sampleCapability}`,
    `SETTLE_DEMO_AMOUNT_LAMPORTS=10000`,
    "",
    `# Settle facilitator endpoint. Devnet: https://settle.so (or self-host).`,
    `SETTLE_ENDPOINT=https://settle.so`,
    "",
  ].join("\n");
  writeFileSync(join(dir, ".env.template"), envTemplate);

  // 5. merchant.md README.
  const readme = [
    `# Settle merchant: ${name}`,
    "",
    `Generated by \`create-settle-merchant\`. Each file documented below.`,
    "",
    `## Files`,
    "",
    `- \`merchant.keypair.json\` — 64-byte secret key as a JSON array. `,
    `  \`solana program deploy --keypair merchant.keypair.json\` and `,
    `  \`anchor\` both consume this format. The matching pubkey is`,
    `  \`${merchant.publicKey.toBase58()}\`.`,
    "",
    `- \`.env.template\` — copy this to \`.env\` (gitignored) and source it in`,
    `  your server runtime.`,
    "",
    `## Wiring up an MCP server (F5.7)`,
    "",
    "```ts",
    `import { wrapWithSettle } from "@settle/mcp-middleware";`,
    "",
    "server.setRequestHandler(CallToolRequestSchema, wrapWithSettle({",
    "  handler: yourExistingHandler,",
    "  pricing: {",
    "    example: {",
    `      capability_hash: "${sampleCapability}",`,
    `      amount_lamports: "10000",`,
    "    },",
    "  },",
    `  settleEndpoint: process.env.SETTLE_ENDPOINT!,`,
    `  merchantPubkey: process.env.MERCHANT_PUBKEY!,`,
    "}));",
    "```",
    "",
    `## Wiring up plain HTTP`,
    "",
    "```ts",
    `import { requireSettleCredential } from "@settle/mcp-middleware";`,
    "",
    "const checkPayment = requireSettleCredential({",
    "  pricing: {",
    `    capability_hash: "${sampleCapability}",`,
    `    amount_lamports: "10000",`,
    "  },",
    `  settleEndpoint: process.env.SETTLE_ENDPOINT!,`,
    `  merchantPubkey: process.env.MERCHANT_PUBKEY!,`,
    "});",
    "",
    "// In your handler:",
    "const result = await checkPayment(req.headers);",
    `if (!result.allowed) return new Response("payment required", { status: 402 });`,
    "// ... continue",
    "```",
    "",
    `## Embeddable pay button (F5.4)`,
    "",
    "```html",
    `<script src="https://settle.so/pay.js"></script>`,
    `<settle-pay`,
    `  merchant="${merchant.publicKey.toBase58()}"`,
    `  amount="0.50"`,
    `  note="Order #1234"`,
    `></settle-pay>`,
    "```",
    "",
    `## Embeddable verification (F5.5)`,
    "",
    "```html",
    `<script src="https://settle.so/verify.js"></script>`,
    `<settle-verify hash="<32-byte-hex>"></settle-verify>`,
    "```",
    "",
    `## Register your capability alias (F3.4)`,
    "",
    `Submit your capability_hash to /capabilities so users see "Translate EN→FR"`,
    `instead of \`${sampleCapability.slice(0, 16)}…\`.`,
    "",
    `## Security notes`,
    "",
    `- \`merchant.keypair.json\` is sensitive — never commit it.`,
    `  On Linux/macOS the file is mode 600. On Windows, set ACLs manually.`,
    `- \`SETTLE_WEBHOOK_SIGNING_SECRET\` must match the secret you registered with`,
    `  Settle. Verify webhook signatures via the \`X-Settle-Signature\` header`,
    `  using HMAC-SHA256.`,
    "",
  ].join("\n");
  writeFileSync(join(dir, "merchant.md"), readme);

  // 6. .gitignore so the keypair stays out of git if the dir gets initialized.
  writeFileSync(
    join(dir, ".gitignore"),
    [
      "# F4.1 — never commit the keypair or env file.",
      "merchant.keypair.json",
      ".env",
      ".env.local",
      "",
    ].join("\n"),
  );

  console.log(`✓ Generated ./${name}/`);
  console.log(`  pubkey:           ${merchant.publicKey.toBase58()}`);
  console.log(`  capability_hash:  ${sampleCapability.slice(0, 16)}…`);
  console.log(`  webhook secret:   (32 bytes, in .env.template)`);
  console.log("");
  console.log("Next:");
  console.log(`  1. cd ${name}`);
  console.log(`  2. cp .env.template .env  # then fill in MERCHANT_WEBHOOK_URL`);
  console.log(`  3. Install @settle/mcp-middleware in your server.`);
  console.log(`  4. Register your alias at https://settle.so/capabilities`);
}

main();
