#!/usr/bin/env tsx
/**
 * F9.3 — End-to-end PoC for receipt federation.
 *
 * What it does:
 *   1. Generates a fresh Ed25519 attestation keypair.
 *   2. Inserts a row into federation_origins with that pubkey
 *      (origin_id = "settle-poc-{timestamp}", trusted = false).
 *   3. Builds a sample foreign payload (x402-shaped: from/to/amount).
 *   4. Computes payload_hash = sha256(canonical_json(payload)).
 *   5. Signs `payload_hash || origin_id || remote_request_id` with the
 *      attestation key.
 *   6. POSTs to /api/federation/import.
 *   7. Asserts the response is `ok: true`, `status: "untrusted"`
 *      (because trusted=false at registration).
 *   8. Promotes the origin to trusted via Supabase RPC, re-imports,
 *      asserts status now flips to `verified` on next import.
 *
 * Run:
 *   pnpm tsx scripts/federation-attest.ts \
 *     --base http://localhost:3000
 *
 * Optional: --base defaults to http://localhost:3000.
 */

import { ed25519 } from "@noble/curves/ed25519";
import bs58 from "bs58";
import { sha256 } from "@noble/hashes/sha2";
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "node:fs";

interface Args {
  base: string;
}

function parseArgs(): Args {
  const args: Args = { base: "http://localhost:3000" };
  for (let i = 2; i < process.argv.length; i += 1) {
    const a = process.argv[i];
    if (a === "--base" && i + 1 < process.argv.length) {
      args.base = process.argv[i + 1]!;
      i += 1;
    }
  }
  return args;
}

function loadDotEnvLocal(): Record<string, string> {
  try {
    return readFileSync(".env.local", "utf8")
      .split("\n")
      .filter((l) => l && !l.startsWith("#"))
      .reduce<Record<string, string>>((acc, line) => {
        const [k, ...rest] = line.split("=");
        if (k) acc[k.trim()] = rest.join("=").trim();
        return acc;
      }, {});
  } catch {
    return {};
  }
}

function canonical(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + canonical(obj[k])).join(",") + "}";
}

function bytesToHex(b: Uint8Array): string {
  return Array.from(b)
    .map((v) => v.toString(16).padStart(2, "0"))
    .join("");
}

async function main() {
  const args = parseArgs();
  const env = { ...loadDotEnvLocal(), ...process.env };

  const supabaseUrl = env.SUPABASE_URL ?? env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey =
    env.SUPABASE_SERVICE_ROLE_KEY ?? env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !supabaseKey) {
    console.error(
      "[fed-poc] SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY required in env or .env.local",
    );
    process.exit(2);
  }
  const sb = createClient(supabaseUrl, supabaseKey, { auth: { persistSession: false } });

  // 1. Generate keypair.
  const sk = ed25519.utils.randomPrivateKey();
  const pk = ed25519.getPublicKey(sk);
  const pkB58 = bs58.encode(pk);
  const originId = `settle-poc-${Date.now()}`;
  console.log("[fed-poc] origin_id:", originId);
  console.log("[fed-poc] attestation_pubkey:", pkB58);

  // 2. Register origin.
  const { error: insErr } = await sb.from("federation_origins").insert({
    origin_id: originId,
    label: "Settle federation PoC",
    attestation_pubkey: pkB58,
    trusted: false,
    notes: "Auto-generated by scripts/federation-attest.ts",
  });
  if (insErr) {
    console.error("[fed-poc] failed to register origin:", insErr.message);
    process.exit(1);
  }
  console.log("[fed-poc] registered origin (trusted=false)");

  // 3. Build sample x402-shaped payload.
  const remoteRequestId = `req-${crypto.randomUUID()}`;
  const payload = {
    from: "B4cArR1M1MySM4dn4HeDdifdPiF98wTNmbzKYg6to2Cp",
    to: "C9HAssvFBtEgHvZRVGdfxcUwrGfu5iK4Z3FKn52Ns7yY",
    amount_lamports: "200000",
    asset: "USDC",
    capability: "translate.demo.x402/POST/v1",
    purpose: "PoC federation attestation",
    timestamp: new Date().toISOString(),
  };

  // 4. Compute payload hash.
  const canonicalStr = canonical(payload);
  const payloadHash = bytesToHex(sha256(new TextEncoder().encode(canonicalStr)));
  console.log("[fed-poc] payload_hash:", payloadHash);

  // 5. Sign attestation.
  const message = `${payloadHash}|${originId}|${remoteRequestId}`;
  const sig = ed25519.sign(new TextEncoder().encode(message), sk);
  const sigB58 = bs58.encode(sig);

  // 6. POST to /api/federation/import.
  const importUrl = `${args.base}/api/federation/import`;
  let res = await fetch(importUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      origin_id: originId,
      remote_request_id: remoteRequestId,
      payload,
      attestation_sig_b58: sigB58,
    }),
  });
  let json = await res.json();
  if (!res.ok || !json.ok) {
    console.error("[fed-poc] import failed:", res.status, json);
    process.exit(1);
  }
  if (json.federated_receipt.status !== "untrusted") {
    console.error(
      "[fed-poc] expected status='untrusted' on first import, got:",
      json.federated_receipt.status,
    );
    process.exit(1);
  }
  console.log("[fed-poc] [OK] first import — status='untrusted' (origin not yet promoted)");

  // 7. Promote origin to trusted, re-import (idempotent on (origin_id, remote_request_id)).
  await sb.from("federation_origins").update({ trusted: true }).eq("origin_id", originId);
  res = await fetch(importUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      origin_id: originId,
      remote_request_id: remoteRequestId,
      payload,
      attestation_sig_b58: sigB58,
    }),
  });
  json = await res.json();
  if (!json.ok || json.federated_receipt.status !== "verified") {
    console.error(
      "[fed-poc] expected status='verified' after promotion, got:",
      json.federated_receipt?.status ?? "<no row>",
    );
    process.exit(1);
  }
  console.log("[fed-poc] [OK] re-import — status='verified' (origin trusted, sig matches)");
  console.log("[fed-poc] [OK] federation_id:", json.federated_receipt.federated_id);

  // 8. Negative test: tamper with payload, sig should fail.
  const tampered = { ...payload, amount_lamports: "999999999" };
  res = await fetch(importUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      origin_id: originId,
      remote_request_id: `req-${crypto.randomUUID()}`,
      payload: tampered,
      attestation_sig_b58: sigB58, // sig still binds to original payload
    }),
  });
  json = await res.json();
  if (res.status === 401 && json.error === "bad_attestation") {
    console.log("[fed-poc] [OK] tamper test — 401 bad_attestation as expected");
  } else {
    console.error(
      "[fed-poc] tamper test FAILED — expected 401 bad_attestation, got:",
      res.status,
      json,
    );
    process.exit(1);
  }

  console.log("[fed-poc] [OK] all checks passed");
}

main().catch((e) => {
  console.error("[fed-poc] fatal:", e);
  process.exit(1);
});
